# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

resources:
  repositories:
  - repository: MyRepo
    type: github
    name: ionellu/Sdl-Community
    
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - Sdl-Community/AdvancedDisplayFilter/*

pool: mypool

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution : '**/Sdl.Community.AdvancedDisplayFilter.sln'
  
steps:
  - template: include-buid-steps.yml  # Template reference