# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core


resources:
  repositories:
  - repository: MyRepo  # identifier (A-Z, a-z, 0-9, and underscore)
    type: github  # see the following "Type" topic
    name: ionellu/Sdl-Community  # repository name (format depends on `type`)
    endpoint: ionellu  # name of the service connection to use (for types that aren't Azure Repos)
trigger:
  branches:
    include:
      - MyRepo.master
  paths:
    include:
      - Sdl-Community/AdvancedDisplayFilter/*

pool: mypool

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution : '**/Sdl.Community.AdvancedDisplayFilter.sln'
  
steps:
  - checkout: MyRepo
  - template: include-buid-steps.yml  # Template reference